name: murobird
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === Runtime (deben ir aquí, no en dev_dependencies) ===
  permission_handler: ^12.0.1
  record: ^6.1.1
  path_provider: ^2.1.4
  tflite_flutter: ^0.11.0
  fftea: ^1.0.0
  http: ^1.2.2  
  audioplayers: ^5.2.1
  url_launcher: ^6.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    # Imágenes
    - assets/images/logo.png
    - assets/images/logo_birby.png
    - assets/images/murobird_sinfondo.png
    # Mock/demos
    - assets/mock/espectrograma_demo.png
    - assets/mock/spectrogram_demo.png
    - assets/mock/mapa_demo.png
    - assets/mock/wave_demo.png
    - assets/mock/bird_1.jpg
    - assets/mock/bird_2.jpg
    - assets/mock/bird_3.jpg
    - assets/mock/bird_4.jpg
    # Modelos BirdNET
    - assets/models/birdnet/audio-model-fp16.tflite
    - assets/models/birdnet/meta-model.tflite
    # Puedes incluir el directorio de labels completo
    - assets/models/birdnet/labels/
    - assets/mock/
    

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#10A37F"
